### ISSUE TITLE
Slack app works when run locally, but fails once deployed: Caught error from user supplied module: NotFound: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by au-re** [slackapi/deno-slack-sdk#146]
Hi! I've followed the tutorials and adapted it to create a simple slack app that reacts to mentions. I bootstraped the project with  `slack create` and I picked the hello world example. 

The app works when I run it locally with `slack run`. There are also no errors when I run `slack deploy`. I made sure to create the triggers and added the necessary scopes to the manifest. However when I want to test the deployed app nothing happens. These are the logs I get from running `slack activity`:

```
2023-03-04 15:09:26 [info] [Fn04SD5DNPV1] (Trace=Tr04SRV005BK) Function execution started for app function 'Provide an answer'
2023-03-04 15:09:27 [info] [Fn04SD5DNPV1] (Trace=Tr04SRV005BK) Function execution output:
        Caught error from user supplied module: NotFound: No such file or directory (os error 2)
        at async run (file:///opt/runtime.js:1719:29)
        at async serveHttp (file:///opt/runtime.js:1749:38)
2023-03-04 15:09:28 [error] [Fn04SD5DNPV1] (Trace=Tr04SRV005BK) Function execution failed for function 'Provide an answer'
        event_dispatch_failed
2023-03-04 15:09:28 [error] [Wf04SD977A10] (Trace=Tr04SRV005BK) Execution failed for workflow step 'Provide an answer'
2023-03-04 15:09:29 [error] [Fn04SFNUG8PN] (Trace=Tr04SD6LHT27) Function execution failed for function 'Handle user query'
        Function failed to execute
2023-03-04 15:09:29 [error] [Wf04SD977A10] (Trace=Tr04SRV005BK) Execution failed for workflow 'Handle user query'
        Function failed to execute
```

It looks like some file goes missing during the deploy but I'm not sure why or how to fix it..

**Comment by filmaj** [comment]
Hey @au-re ! Thanks for writing in, and sorry for the frustrating experience! Hopefully we can get to the bottom of it.

1. What version of our SDK(s) are you using? If you could post the contents of your app's `import_map.json` and `slack.json`, that will help me out.
2. Are you able to share your "Provide an answer" function code as well as function definition?
3. Are you able to share the workflow definition and configuration (i.e. the ways in which workflow's functions are wired up into steps) that contains the "Provide an answer" function?

Something weird is going on as, during `slack deploy`, we bundle all your code into a single .js file. If there would be any issues in importing your app's modules - which seems to be somewhat the issue here - I would expect that `slack deploy` would raise the issue then.

**Comment by au-re** [comment]
Thanks @filmaj!

import_map.json
```
{
  "imports": {
    "deno-slack-sdk/": "https://deno.land/x/deno_slack_sdk@1.6.0/",
    "deno-slack-api/": "https://deno.land/x/deno_slack_api@1.7.0/"
  }
}
```
slack.json
```
{
  "hooks": {
    "get-hooks": "deno run -q --allow-read --allow-net https://deno.land/x/deno_slack_hooks@0.9.3/mod.ts"
  }
}
```
function definition
```
import { DefineFunction, Schema, SlackFunction } from "deno-slack-sdk/mod.ts";

const queryServiceBaseURL = "xxx";
const queryPath = "/v1/query";

/**
 * Functions are reusable building blocks of automation that accept
 * inputs, perform calculations, and provide outputs. Functions can
 * be used independently or as steps in workflows.
 * https://api.slack.com/future/functions/custom
 */
export const ProvideAnswerFunctionDefinition = DefineFunction({
  callback_id: "provide_answer",
  title: "Provide an answer",
  description: "Provide an answer to a query",
  source_file: "functions/provide_answer.ts",
  input_parameters: {
    properties: {
      message: {
        type: Schema.types.string,
        description: "User query",
      },
    },
    required: ["message"],
  },
  output_parameters: {
    properties: {
      answer: {
        type: Schema.types.string,
        description: "Answer to the user query",
      },
    },
    required: ["answer"],
  },
});

export default SlackFunction(
  ProvideAnswerFunctionDefinition,
  async ({ inputs }) => {
    try {
      const { message } = inputs;

      const resp = await fetch(`${queryServiceBaseURL}${queryPath}`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ query: message }),
      });

      const { answer } = await resp.json();
      return { outputs: { answer } };
    } catch (error) {
      console.log(error);
      return { outputs: { answer: "oh no something went wrong..." } };
    }
  }
);
```
workflow
```
import { DefineWorkflow, Schema } from "deno-slack-sdk/mod.ts";
import { ProvideAnswerFunctionDefinition } from "../functions/provide_answer.ts";

const HandleQueryFlow = DefineWorkflow({
  callback_id: "handle_query",
  title: "Handle user query",
  description: "Handle user query",
  input_parameters: {
    properties: {
      message: {
        type: Schema.types.string,
      },
      user: {
        type: Schema.slack.types.user_id,
      },
      channel: {
        type: Schema.slack.types.channel_id,
      },
    },
    required: ["message"],
  },
});

const ProvideAnswerStep = HandleQueryFlow.addStep(
  ProvideAnswerFunctionDefinition,
  {
    message: HandleQueryFlow.inputs.message,
  }
);

HandleQueryFlow.addStep(Schema.slack.functions.SendMessage, {
  channel_id: HandleQueryFlow.inputs.channel,
  message: ProvideAnswerStep.outputs.answer,
});

export default HandleQueryFlow;
```

I tried deploying again today, with the same result

**Comment by filmaj** [comment]
Something weird happening in here for sure... if you don't mind bearing with me, we can maybe get to the bottom of it by inspecting the generated bundle of your app.

1. Run the following command from your app directory: `deno run -q --config=deno.jsonc --allow-read --allow-write --allow-net --allow-run --allow-env https://deno.land/x/deno_slack_builder@0.2.2/mod.ts`. 
2. This should create a `dist/` directory in your app. Can you paste the contents of the `dist/manifest.json` file, and specifically the contents of the top-level `functions` key?
3. Can you then also paste the directory listing for the `dist/functions` directory?

**Comment by au-re** [comment]
hi! sorry for the late reply, here is the manifest.json file from the dist folder:

dist/manifest.json
```
{
  "_metadata": {
    "major_version": 2
  },
  "display_information": {
    "name": "pufflybot",
    "description": "Ask me things about your projects"
  },
  "icon": "assets/app_icon.png",
  "oauth_config": {
    "scopes": {
      "bot": [
        "app_mentions:read",
        "commands",
        "chat:write",
        "chat:write.public",
        "datastore:read",
        "datastore:write",
        "channels:read",
        "triggers:write"
      ]
    },
    "token_management_enabled": false
  },
  "features": {
    "bot_user": {
      "display_name": "pufflybot"
    },
    "app_home": {
      "messages_tab_enabled": true,
      "messages_tab_read_only_enabled": true
    }
  },
  "settings": {
    "function_runtime": "slack",
    "org_deploy_enabled": true
  },
  "functions": {
    "provide_answer": {
      "title": "Provide an answer",
      "description": "Provide an answer to a query",
      "input_parameters": {
        "properties": {
          "message": {
            "type": "string",
            "description": "User query"
          }
        },
        "required": [
          "message"
        ]
      },
      "output_parameters": {
        "properties": {
          "answer": {
            "type": "string",
            "description": "Answer to the user query"
          }
        },
        "required": [
          "answer"
        ]
      }
    }
  },
  "workflows": {
    "handle_query": {
      "title": "Handle user query",
      "description": "Handle user query",
      "input_parameters": {
        "properties": {
          "message": {
            "type": "string"
          },
          "user": {
            "type": "slack#/types/user_id"
          },
          "channel": {
            "type": "slack#/types/channel_id"
          }
        },
        "required": [
          "message"
        ]
      },
      "steps": [
        {
          "id": "0",
          "function_id": "#/functions/provide_answer",
          "inputs": {
            "message": "{{inputs.message}}"
          }
        },
        {
          "id": "1",
          "function_id": "slack#/functions/send_message",
          "inputs": {
            "channel_id": "{{inputs.channel}}",
            "message": "{{steps.0.answer}}"
          }
        }
      ]
    }
  },
  "outgoing_domains": [
    "xxx.ondigitalocean.app"
  ]
}
```

the functions folder contains a single file:
```provide_answer.js```

**Comment by tomas-zijdemans-vipps** [comment]
Probably not the solution, but just checking:
"the functions folder contains a single file:
provide_answer.js"
Could the problem be that the file should be a .ts file? (or was that a type and you meant to write provide_answer.ts?)

**Comment by shapirone** [comment]
So sorry that you're still running into this issue @au-re! We're still investigating and would like to make two more requests:

1. Can you please run the `slack doctor` command and share the output? Please obfuscate personal details, but we'd like to know your operating system, Deno version, dependency versions, and number of authenticated workspaces 🙇 
2. Do you experience this issue with an out of the box sample? Would be very helpful to know if you're able to deploy the hello world sample without any modifications.


> Could the problem be that the file should be a .ts file? (or was that a type and you meant to write provide_answer.ts?)

This looks correct. Our bundling process outputs `js` files into `dist/functions`, rather than `ts` files. The original `source_file` was correctly `provide_answer.ts`.

**Comment by filmaj** [comment]
Closing this issue for inactivity. @au-re if you are able to try @shapirone's suggestion above, feel free to re-open and comment.
