### ISSUE TITLE
Option to use mutual TLS requests verification mechanism in workflows

### ISSUE THREAD

**Issue by hqp468** [slackapi/deno-slack-sdk#357]
Hi,

Is it possible to use mTLS with Workflow apps that are hosted on Slack infra?
https://api.slack.com/authentication/verifying-requests-from-slack

For now we get the following error:
`
main cause of error as Caused by Error: received fatal alert: CertificateRequired
Please find the log file from the slack server as below if it helps:
TypeError: body failed
at mainFetch (ext:deno_fetch/26_fetch.js:181:11)
at eventLoopTick (ext:core/01_core.js:168:7)
at async fetch (ext:deno_fetch/26_fetch.js:391:7)
at async AsyncFunction.<anonymous> (file:///var/task/functions/create_jira_issue_function.js:4290:33)
at async Object.RunFunction [as function_executed] (file:///opt/runtime.js:1683:55)
at async DispatchPayload (file:///opt/runtime.js:1790:16)
at async run (file:///opt/runtime.js:1857:18)
at async serveHttp (file:///opt/runtime.js:1885:38)
Caused by Error: received fatal alert: CertificateRequired
at mainFetch (ext:deno_fetch/26_fetch.js:181:49)
at eventLoopTick (ext:core/01_core.js:168:7)
at async fetch (ext:deno_fetch/26_fetch.js:391:7)
at async AsyncFunction.<anonymous> (file:///var/task/functions/create_jira_issue_function.js:4290:33)
at async Object.RunFunction [as function_executed] (file:///opt/runtime.js:1683:55)
at async DispatchPayload (file:///opt/runtime.js:1790:16)
at async run (file:///opt/runtime.js:1857:18)
at async serveHttp (file:///opt/runtime.js:1885:38)
`

**Comment by WilliamBergamin** [comment]
Closing due to inactivity
