### ISSUE TITLE
[BUG] < Packaging app for deployment✘ [ERROR] Cannot convert undefined or null to object [plugin deno-loader]>

### ISSUE THREAD

**Issue by MitchDevLissi** [slackapi/deno-slack-sdk#374]
Hello, 
basically, I am developing a trigger, and with slack run, it runs smoothly, but with slack deploy, I have the following error:

`
⠼ Packaging app for deployment✘ [ERROR] Cannot convert undefined or null to object [plugin deno-loader]
Error bundling function file "function" with esbuild
error: Uncaught (in promise) Error: Build failed with 1 error:
error: Cannot convert undefined or null to object
  let error = new Error(text);
              ^
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.19.4/mod.js:1626:15)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1035:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.19.4/mod.js:1461:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.19.4/mod.js:1033:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1062:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.19.4/mod.js:679:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.19.4/mod.js:739:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.19.4/mod.js:655:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1924:11
    at eventLoopTick (ext:core/01_core.js:175:7)
Packaging app for deployment`
I'm Using: 
slack v2.30.1
deno 2.0.4 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2

Actually, I have this error even with empty functions basically, what could it be? 

Thanks a lot! 

**Requirements**

Please read the [Contributing guidelines](https://github.com/slackapi/deno-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
Can you try downgrading deno to 1.x? E.g. 1.46.3 is the last deno 1.x version. I think you can do that with `deno upgrade --version 1.46.3`.

For context, here is what's happening:

1. As part of `slack deploy`, we "bundle" your app into a single `.js` file.
2. This bundling uses `esbuild` under the hood (as native bundling tools in deno have been deprecated / removed).
3. `esbuild` has not been great for us here, there are many situations where it fails 😢 (see e.g #316 and https://github.com/slackapi/deno-slack-hooks/issues/89). It regularly fails to bundle when using more complex npm dependencies, or on Windows, for example.

**Comment by MitchDevLissi** [comment]
I updated it, I changed the import_map.json, I followed this guide for the environment variables (https://api.slack.com/automation/environment-variables#access-function)
Now I have this error 
Uncaught (in promise) TypeError: Requires net access to "esm.sh:443", run again with the --allow-net flag

Here 
import { authenticate } from '@google-cloud/local-auth';

So with the newer version of Deno, I can deploy, but then it does not work, with the older version of Deno, I can deploy, but then when the function is running, it gives the specified error. 
Thanks for the support!

**Comment by MitchDevLissi** [comment]
import_map.json
`{
  "imports": {
    "deno-slack-sdk/": "https://deno.land/x/deno_slack_sdk@2.14.2/",
    "deno-slack-api/": "https://deno.land/x/deno_slack_api@2.8.0/",
    "microsoft-graph-client": "https://esm.sh/@microsoft/microsoft-graph-client@3.0.7",
    "microsoft-graph-types": "https://esm.sh/@microsoft/microsoft-graph-types@2.40.0",
    "std/": "https://deno.land/std@0.202.0/",
    "@google-cloud/local-auth": "https://esm.sh/@google-cloud/local-auth@2.1.0",
    "googleapis": "https://esm.sh/googleapis@39.2.0"
  }
}`

Slack.json

`{
  "hooks": {
    "get-hooks": "deno run --allow-all https://deno.land/x/deno_slack_hooks/mod.ts"
  }
}
`

**Comment by filmaj** [comment]
Thanks.

> So with the newer version of Deno, I can deploy, but then it does not work, with the older version of Deno, I can deploy, but then when the function is running, it gives the specified error.

In the sentence above you say "I can deploy" in both cases - I think one of these is supposed to be "cannot", yes?

Try adding `esm.sh` to your `manifest.ts`' `outgoingDomains` array; that should fix the issue when running locally, which I believe is where you are seeing the issue right now.

In general, if/until the deployed environment supports deno 2 (it currently runs on 1.46.2 which you can always check by looking at the `deno-runtime` property in https://api.slack.com/slackcli/metadata.json), we recommend using the same version of deno locally as Slack runs in the cloud when running your app, to ensure identical behaviour.

**Comment by MitchDevLissi** [comment]
What u mean 'adding adding esm.sh to your manifest.ts' outgoingDomains array'?
Exactly, I can deploy but not running locally with 1.46.3, and I can t deploy but running locally with the newer version

**Comment by filmaj** [comment]
See [the `outgoingDomains` field documentation of your App Manifest](https://api.slack.com/automation/manifest#manifest-properties). [Here is a sample with an example](https://github.com/slack-samples/deno-message-translator/blob/d25a0c270846d8ffaa1759c7b3f777cdf63a3360/manifest.ts#L31). Add `esm.sh` to this field.

**Comment by ThisGuyCodes** [comment]
> In general, if/until the deployed environment supports deno 2 (it currently runs on 1.46.2 which you can always check by looking at the deno-runtime property in [api.slack.com/slackcli/metadata.json](https://api.slack.com/slackcli/metadata.json)), we recommend using the same version of deno locally as Slack runs in the cloud when running your app, to ensure identical behaviour.

I installed the slack CLI like this:
```shell
brew install slack-cli
```

This automatically installed Deno 2.x. If this is not supported it may be a good idea to update the Homebrew recipe to reflect a supported setup.

**Comment by WilliamBergamin** [comment]
Closing dues to inactivity 

Refer to Slack official documentation when installing the [Slack CLI](https://tools.slack.dev/slack-cli/) on [MacOS/Linux](https://tools.slack.dev/slack-cli/guides/installing-the-slack-cli-for-mac-and-linux) and [Windows](https://tools.slack.dev/slack-cli/guides/installing-the-slack-cli-for-windows)
