### ISSUE TITLE
[BUG] Unable to use Google APIs in a deno slack app

### ISSUE THREAD

**Issue by mversluys** [slackapi/deno-slack-sdk#375]
**The `deno-slack` versions**

```
    "deno-slack-sdk/": "https://deno.land/x/deno_slack_sdk@2.14.2/",
    "deno-slack-api/": "https://deno.land/x/deno_slack_api@2.8.0/",
```

**Deno runtime version**

```
deno 2.0.2 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
```

**OS info**

```
ProductName:		macOS
ProductVersion:		15.1
BuildVersion:		24B83
Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:26 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8122
```

**Describe the bug**

Unable to make use of Google deno packages.

I'm attempting to import the Google sheets API using 
```
import { Sheets, auth as GoogleAuth } from 'https://googleapis.deno.dev/v1/sheets:v4.ts';
``` 

This was working earlier in the year and I have a deployed application that utilizes this, but now when I use `slack run` I get the following error 

```
error: Uncaught (in promise) TypeError: Requires import access to "googleapis.deno.dev:443", run again with the --allow-import flag
```

I've searched high and low and tried add --allow-import to get-hooks in slack.json but haven't be able to find a way to convince deno to allow the import of the google APIs. I reached out to Slack support and they directed me here.

**Steps to reproduce**

1. Clone the deno starter template https://github.com/slack-samples/deno-starter-template
2. In functions/sample_function.ts, add 
```
import { Sheets, auth as GoogleAuth } from 'https://googleapis.deno.dev/v1/sheets:v4.ts';
``` 
3. Run the project using `slack run`

**Expected result**

Expect that I'm able to import google deno packages.

**Actual result**

It fails with the following error
```
error: Uncaught (in promise) TypeError: Requires import access to "googleapis.deno.dev:443", run again with the --allow-import flag
```

**Requirements**

Please read the [Contributing guidelines](https://github.com/slackapi/deno-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
Try adding `googleapis.deno.dev` to the `outgoingDomains` array of your app manifest.

https://api.slack.com/automation/manifest

**Comment by jphchan** [comment]
I get the same thing when attempting to follow the slack announcement bot tutorial. Running step 6 where you create the trigger it fails with the same message. I. My case it fails trying to reach cdn.skypack.dev.  I checked and the demo apps manifest includes the outgoing domains section and lists the location so I don’t think that’s it.

**Comment by zimeg** [comment]
@ledmonster Is this request happening while the app manifest `outgoingDomains` includes "googleapis.deno.dev"?

🔍 Reference: https://github.com/slack-samples/deno-github-functions/blob/f0177a63f43080c0ed1f2fb250ff1e5b4ee61c7b/manifest.ts#L16-L21

**Comment by ledmonster** [comment]
@zimeg yes, I configured `outgoingDomains` for "googleapis.deno.dev".
here are my library versions:
- deno: 2.3.5
- deno-slack-sdk: 2.15.1
- deno_slack_api: 2.8.0

I don't know why deno-slack-runtime uses deno-slack-builder 0.0.14 (old and looks deprecated).
- https://github.com/slackapi/deno-slack-runtime/blob/main/src/deps.ts

**Comment by ledmonster** [comment]
@zimeg the difference between `slack-samples/deno-github-functions` and this issue is that the sample only requests to "api.github.com", while `https://googleapis.deno.dev/v1/sheets:v4.ts` is used as an import statement.

**Comment by zimeg** [comment]
@ledmonster Thanks so much for sharing these details - I think we're now getting to the root cause 🤖

I find a few changes to the `.slack/hooks.json` file let's us generate a manifest and start the app:

```json
{
  "hooks": {
    "get-hooks": "deno run -q --allow-read --allow-net https://deno.land/x/deno_slack_hooks@1.4.0/mod.ts",
    "get-manifest": "deno run -q --config=deno.jsonc --allow-read --allow-net --allow-env --allow-sys=osRelease --allow-import=deno.land:443,googleapis.deno.dev:443,jsr.io:443 https://deno.land/x/deno_slack_hooks@1.4.0/get_manifest.ts",
    "get-trigger": "deno run -q --config=deno.jsonc --allow-read --allow-net --allow-env --allow-import=deno.land:443,googleapis.deno.dev:443,jsr.io:443 https://deno.land/x/deno_slack_hooks@1.4.0/get_trigger.ts",
    "start": "deno run -q --config=deno.jsonc --allow-read --allow-net --allow-run --allow-env --allow-sys=osRelease --allow-import=deno.land:443,googleapis.deno.dev,jsr.io:443 https://deno.land/x/deno_slack_runtime@1.1.3/local-run.ts"
  }
}
```

🔍 The big change above is `--allow-import=deno.land:443,googleapis.deno.dev,jsr.io:443` to update [network](https://docs.deno.com/runtime/fundamentals/security/#network-access) access.

Later on a function execution, this runtime error appears that points to the [`deno-slack-builder`](https://github.com/slackapi/deno-slack-builder?tab=readme-ov-file) project as you callout:

```
error: Uncaught (in promise) TypeError: Requires import access to "googleapis.deno.dev:443", run again with the --allow-import flag
    at file:///private/tmp/slack/hopeful-anteater-484/functions/sample_function.ts:4:44
    const manifestJSFile = await import(`file://${manifestJSFilePath}`);
                           ^
    at async readImportedManifestFile (https://deno.land/x/deno_slack_builder@0.0.14/manifest.ts:101:28)
    at async createManifest (https://deno.land/x/deno_slack_builder@0.0.14/manifest.ts:19:22)
    at async runLocally (https://deno.land/x/deno_slack_runtime@1.1.3/local-run-function.ts:21:20)
    at async https://deno.land/x/deno_slack_runtime@1.1.3/local-run-function.ts:55:3
```

And that leads to the [calling code](https://github.com/slackapi/deno-slack-runtime/blob/bfabe43594d142148bf2fc709065a792fcca97ce/src/local-run-function.ts#L53-L62) which has [a pending update](https://github.com/slackapi/deno-slack-runtime/blob/bfabe43594d142148bf2fc709065a792fcca97ce/src/deps.ts#L4-L5) to use the `get-manifest` hook instead of the builder. 🧱 

IIRC the allowed imports should match outgoing domains, but I also think these hook customization should work. For now let's change this to a `bug` to investigate using the `get-manifest` hook for these customizations!

**Comment by ledmonster** [comment]
@zimeg thank you. The issue only affects the "slack run", and we can still deploy the code, right?

When does the team plan to fix the issue?

**Comment by ledmonster** [comment]
@zimeg could you please release a new [deno-slack-runtime](https://github.com/slackapi/deno-slack-runtime) version? We need it to fix the issue.
