### ISSUE TITLE
[BUG] bundling error with plugin deno-loader

### ISSUE THREAD

**Issue by scott-paige** [slackapi/deno-slack-sdk#378]
**The `deno-slack` versions**

```
"deno-slack-sdk/": "https://deno.land/x/deno_slack_sdk@2.14.2/",
"deno-slack-api/": "https://deno.land/x/deno_slack_api@2.8.0/",
```

**Deno runtime version**

```
deno -v
deno 2.0.5
```

**OS info**
```
ProductName:		macOS
ProductVersion:		14.6
BuildVersion:		23G80
Darwin Kernel Version 23.6.0: Fri Jul  5 17:56:15 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T6031
```

**Describe the bug**

We have made minimal changes to our code (updated how an env var is used), and when we go to deploy we get numerous errors .  I have tried updating the import_map.json, deleting the deployment, and praying. My co-worker is encountering the same issue on his machine as well.

**Steps to reproduce**
1.  `slack deploy`
2. 
3. 

**Expected result**

For it to bundle and deploy

**Actual result**

```
⠙ Packaging app for deployment✘ [ERROR] NPM package not found. [plugin deno-loader]
    ../../Library/Caches/deno/deno_esbuild/@octokit/auth-app@7.1.2/node_modules/@octokit/auth-app/dist-node/index.js:42:25:
      42 │ import { LRUCache } from "lru-cache";
         ╵                          ~~~~~~~~~~~
✘ [ERROR] invalid empty host: '.' [plugin deno-loader]
    https://deno.land/x/deno_slack_sdk@2.14.2/schema/slack/functions/mod.ts:2:24:
      2 │ import AddBookmark from "./add_bookmark.ts";
```
```
Error bundling function file "trigger_github_workflow_function" with esbuild
error: Uncaught (in promise) Error: Build failed with 58 errors:
../../Library/Caches/deno/deno_esbuild/@octokit/auth-app@7.1.2/node_modules/@octokit/auth-app/dist-node/index.js:42:25: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@octokit/auth-oauth-user@5.1.1/node_modules/@octokit/auth-oauth-user/dist-bundle/index.js:9:38: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@octokit/auth-oauth-user@5.1.1/node_modules/@octokit/auth-oauth-user/dist-bundle/index.js:10:36: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@octokit/request@9.1.3/node_modules/@octokit/request/dist-bundle/index.js:2:25: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/universal-github-app-jwt@2.2.0/node_modules/universal-github-app-jwt/lib/get-token.js:12:42: ERROR: [plugin: deno-loader] NPM package not found.
...
  let error = new Error(text);
              ^
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.19.4/mod.js:1626:15)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1035:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.19.4/mod.js:1461:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.19.4/mod.js:1033:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1062:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.19.4/mod.js:679:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.19.4/mod.js:739:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.19.4/mod.js:655:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1924:11
    at eventLoopTick (ext:core/01_core.js:175:7
```

**Requirements**

Please read the [Contributing guidelines](https://github.com/slackapi/deno-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by scott-paige** [comment]
Ok I think I resolved this by changing my import statement for the octokit pacakage. 

Originally we had: 

```typescript
import { createAppAuth } from "npm:@octokit/auth-app";
```

That worked locally, but enable to deploy it I had to change it to:

```typescript
import { Octokit } from "https://esm.sh/octokit?dts";
```
